Fix sample viewer API issues from holistic testing, add tooltip
Esri/arcgis-maps-sdk-unity-samples pull request #103
Opened 2023-11-14 01:05 UTC by Jade-JadeH

https://devtopia.esri.com/runtime/normandy/issues/2355
https://devtopia.esri.com/runtime/normandy/issues/2350
https://devtopia.esri.com/runtime/normandy/issues/2362

- [ ] Fixed the known issue that enter API key in project settings doesn't unlock the samples reported by holistic sample users 
- [ ] Make the warning message comes and go as users enter and remove API keys in the entry box (project settings doesn't update in runtime though)

2023-11-15 16:50 UTC, mmgaw113 reviewed
Looks good. I'll approve after you deal with merge conflicts and then I will approve.

2023-11-15 17:35 UTC, avr757 requested changes
Looks good and the tooltip works great! 

Just one small change - for the Note, the gap between the title and paragraph can be reduced a little bit (may need to shorten the menu vertically) when the first sentence "Don't forget to enter your API key" is removed from the panel. (just to align with other Notes for consistency purposes).

Current one (more gap between the title and paragraph):
![image](https://github.com/Esri/arcgis-maps-sdk-unity-samples/assets/106696949/2f8bb4e0-4c6b-4329-acaa-54735ad8c1e9)


Notes from other samples (less gap between the title and paragraph):
![image](https://github.com/Esri/arcgis-maps-sdk-unity-samples/assets/106696949/6d0236c5-d08b-4dcd-a2b0-d7c10ad97285)

2023-11-15 22:58 UTC, Jade-JadeH commented
> Just one small change - for the Note, the gap between the title and paragraph can be reduced a little bit (may need to shorten the menu vertically) when the first sentence "Don't forget to enter your API key" is removed from the panel. (just to align with other Notes for consistency purposes).

Good call, I also noticed it but forgot to change

2023-11-15 23:14 UTC, avr757 approved these changes

2023-11-15 23:39 UTC, avr757 approved these changes

2023-11-16 16:35 UTC, mmgaw113 approved these changes

2023-11-16 18:04 UTC, merged