Overhauled VR Sample
Esri/arcgis-maps-sdk-unity-samples pull request #126
Opened 2024-07-30 15:06 UTC by JayPShrestha

Added Unreal functionality/UI to Unity

**Sample**

VR Sample

**Summary**

Overhauled VR Sample to better mirror the current Unreal Engine VR Sample

- Redesigned VR Menu to 5-panel configuration from Unreal
- Changed colors and icons to make VR Menu better mimic the look of the Unreal menu
- Bar providing real time at the top of the menu
- Implemented movement controls for speed and rotation same as Unreal
- Added additional locations of New York, Redlands, and Grand Canyon along with location paging to handle the size
- Implemented weather system with 5 weather types (Sunny, Cloudy, Rainy, Snowy, Thunder) using a dynamic cloud shader, particle systems, VFX systems, and audio taken from Unreal's sample
- Added instruction widget made to look like Unreal's
- Changed tooltips on VR hands in terms of instructions and aesthetic 

**Tests**

Unity 2023.3.19f1
Valve Index

**ArcGIS Maps SDK Version**

1.5.0

2024-07-31 21:57 UTC, ZackAllen requested changes
For every code file:
1. Add the copyright statement.
2. Remove unneeded `using` statements.
3. Run the [codemaid](https://marketplace.visualstudio.com/items?itemName=SteveCadwallader.CodeMaidVS2022) formatter.

2024-07-31 21:57 UTC, ZackAllen commented on xr_sample_project/Assets/SampleViewer/Samples/VRSample/Scripts/InstructionMenu.cs
> +using System.Collections;
```
// Copyright 2022 Esri.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License.
// You may obtain a copy of the License at: http://www.apache.org/licenses/LICENSE-2.0
//
```
This copyright statement should be added to every code file in this sample.

2024-07-31 21:57 UTC, ZackAllen commented on xr_sample_project/Assets/SampleViewer/Samples/VRSample/Scripts/ContinuousMovement.cs
>      private CharacterController controller;
For each code file in this sample, remove the unnecessary `using` statements and run DotNet format.

2024-07-31 21:57 UTC, ZackAllen commented on xr_sample_project/Assets/SampleViewer/Samples/VRSample/Scripts/ContinuousMovement.cs
> +        }
```suggestion
        var yawYValue = moveInLookDirection ? rig.Camera.transform.eulerAngles.y : rightController.transform.eulerAngles.y;
        var yaw = Quaternion.Euler(0, yawYValue, 0);
        var direction = yaw * new Vector3(leftInputAxis.x, 0, leftInputAxis.y);
```

2024-07-31 21:57 UTC, ZackAllen commented on xr_sample_project/Assets/SampleViewer/Samples/VRSample/Scripts/FadeScreen.cs
> +            if(rendererComponent)
```suggestion
            if (rendererComponent)
```

2024-07-31 21:57 UTC, ZackAllen commented on xr_sample_project/Assets/SampleViewer/Samples/VRSample/Scripts/FadeScreen.cs
>      public void FadeIn()
There is a spelling mistake on opacity in this file.

2024-07-31 21:57 UTC, ZackAllen commented on xr_sample_project/Assets/SampleViewer/Samples/VRSample/Scripts/FadeScreen.cs
> +            rendererComponent.material.SetColor("_UnlitColor", lastColor);
```suggestion
            rendererComponent?.material.SetColor("_UnlitColor", lastColor);
```
There is an easier way to check for `null` when calling methods.

2024-07-31 21:57 UTC, ZackAllen commented on xr_sample_project/Assets/SampleViewer/Samples/VRSample/Scripts/InstructionMenu.cs
> +    void Update()
Delete unused code.

2024-07-31 21:57 UTC, ZackAllen commented on xr_sample_project/Assets/SampleViewer/Samples/VRSample/Scripts/InstructionMenu.cs
> +    void Start()
Delete unused method.

2024-07-31 21:57 UTC, ZackAllen commented on xr_sample_project/Assets/SampleViewer/Samples/VRSample/Scripts/LocationSelector.cs
> +        new coordinates("Grand Canyon", -112.0962f, 36.1018f, 1500.0f, 1300f, 250.0f)};
```suggestion
        new coordinates("Christchurch, New Zealand", 172.64f, -43.534f, -331.45f, 40.8f, 542.1f), new coordinates("New York", -74.006f, 40.7128f, -331.45f, 200f, 250.0f), new coordinates("Redlands", -117.196453f, 34.060143f, 1000.05f, 500f, 250.0f), 
        new coordinates("Grand Canyon", -112.0962f, 36.1018f, 1500.0f, 1300f, 250.0f)};
```

2024-07-31 21:57 UTC, ZackAllen commented on xr_sample_project/Assets/SampleViewer/Samples/VRSample/Scripts/LocationSelector.cs
> +    public void GoToNewYork()
These methods are really bad code. Please refactor to not have any method specific to a location. They all just repeat the same few lines.

2024-07-31 21:57 UTC, ZackAllen commented on xr_sample_project/Assets/SampleViewer/Samples/VRSample/Scripts/LocationSelector.cs
> +    void ToggleSlot(CanvasGroup slot, bool state)
```suggestion
    private void ToggleSlot(CanvasGroup slot, bool state)
```

2024-07-31 21:57 UTC, ZackAllen commented on xr_sample_project/Assets/SampleViewer/Samples/VRSample/Scripts/LocationSelector.cs
>      #endregion
```suggestion
    #endregion Public Teleportation Functions
```

2024-07-31 21:57 UTC, ZackAllen commented on xr_sample_project/Assets/SampleViewer/Samples/VRSample/Scripts/SetTurnType.cs
> +    public event ChangedTurnType OnTypeChanged;
```suggestion

    public event ChangedTurnType OnTypeChanged;
```
Formatting

2024-07-31 21:57 UTC, ZackAllen commented on xr_sample_project/Assets/SampleViewer/Samples/VRSample/Scripts/SetTurnType.cs
>      public void SetTurnTypeFromIndex(int index)
Why do we need to set it via index? I feel like this could be avoided wherever this is being called.

2024-07-31 21:57 UTC, ZackAllen commented on xr_sample_project/Assets/SampleViewer/Samples/VRSample/Scripts/SetWeatherType.cs
> +    [SerializeField] WeatherSystem weatherSystem;
```suggestion
    [SerializeField] private WeatherSystem weatherSystem;
```

2024-07-31 21:57 UTC, ZackAllen commented on xr_sample_project/Assets/SampleViewer/Samples/VRSample/Scripts/SetWeatherType.cs
> +        if(weatherSystem)
```suggestion
        if (weatherSystem)
```

2024-07-31 21:57 UTC, ZackAllen commented on xr_sample_project/Assets/SampleViewer/Samples/VRSample/Scripts/SetWeatherType.cs
>          if (index == 0) //Sunny
I suggest a switch statement for this.

2024-07-31 21:57 UTC, ZackAllen commented on xr_sample_project/Assets/SampleViewer/Samples/VRSample/Scripts/SetWeatherType.cs
> +            weatherSystem.SetToSunny();
```suggestion
            weatherSystem?.SetToSunny();
```
If you change these calls, you wont need to check for the weather system on line 22. Will be safer anyway.

2024-07-31 21:57 UTC, ZackAllen commented on xr_sample_project/Assets/SampleViewer/Samples/VRSample/Scripts/TimeBar.cs
> +    void Start()
Remove empty method.

2024-07-31 21:57 UTC, ZackAllen commented on xr_sample_project/Assets/SampleViewer/Samples/VRSample/Scripts/TimeBar.cs
> +        if(timeText != null)
```suggestion
        if (timeText)
```
This should work-

2024-07-31 21:57 UTC, ZackAllen commented on xr_sample_project/Assets/SampleViewer/Samples/VRSample/Scripts/Tooltip.cs
> +    void Start()
Unused method.

2024-07-31 21:57 UTC, ZackAllen commented on xr_sample_project/Assets/SampleViewer/Samples/VRSample/Scripts/Tooltip.cs
> +    bool activeState = true;
```suggestion
    private bool activeState = true;
```

2024-07-31 21:57 UTC, ZackAllen commented on xr_sample_project/Assets/SampleViewer/Samples/VRSample/Scripts/Tooltip.cs
> +    [SerializeField] CanvasGroup tooltipUI;
```suggestion
    [SerializeField] private CanvasGroup tooltipUI;
```

2024-07-31 21:57 UTC, ZackAllen commented on xr_sample_project/Assets/SampleViewer/Samples/VRSample/Scripts/Tooltip.cs
> +        if (toggleMenuButton.triggered)
There must be a better way to do this with the Input system.

2024-07-31 21:57 UTC, ZackAllen commented on xr_sample_project/Assets/SampleViewer/Samples/VRSample/Scripts/Tooltip.cs
> +    void Update()
```suggestion
    private void Update()
```

2024-07-31 21:57 UTC, ZackAllen commented on xr_sample_project/Assets/SampleViewer/Samples/VRSample/Scripts/Tooltip.cs
> +    void EnableTooltip(bool state)
```suggestion
    private void EnableTooltip(bool state)
```

2024-07-31 21:57 UTC, ZackAllen commented on xr_sample_project/Assets/SampleViewer/Samples/VRSample/Scripts/UITextSlider.cs
> +public class UITextSlider : MonoBehaviour
```suggestion

public class UITextSlider : MonoBehaviour
```

2024-07-31 21:57 UTC, ZackAllen commented on xr_sample_project/Assets/SampleViewer/Samples/VRSample/Scripts/UITextSlider.cs
> +    CanvasGroup canvasGroup;
```suggestion
    private CanvasGroup canvasGroup;
    
```

2024-07-31 21:57 UTC, ZackAllen commented on xr_sample_project/Assets/SampleViewer/Samples/VRSample/Scripts/UITextSlider.cs
> +    void Start()
```suggestion
    private void Start()
```

2024-07-31 21:57 UTC, ZackAllen commented on xr_sample_project/Assets/SampleViewer/Samples/VRSample/Scripts/UITextSlider.cs
> +    void ChangeSliderValue(float value)
```suggestion
    private void ChangeSliderValue(float value)
```

2024-07-31 21:57 UTC, ZackAllen commented on xr_sample_project/Assets/SampleViewer/Samples/VRSample/Scripts/UITextSlider.cs
> +                        continuousMovement.SetSpeed(value);
```suggestion
                        continuousMovement?.SetSpeed(value);
```
Do this for the set speed calls and you wont need the null check on 48. Or return early if null.

2024-07-31 21:57 UTC, ZackAllen commented on xr_sample_project/Assets/SampleViewer/Samples/VRSample/Scripts/UITextSlider.cs
> +    void EnableSlider(bool state)
```suggestion
    private void EnableSlider(bool state)
```

2024-07-31 21:57 UTC, ZackAllen commented on xr_sample_project/Assets/SampleViewer/Samples/VRSample/Scripts/UITextSlider.cs
> +    void Update()
Remove unused method.

2024-07-31 21:57 UTC, ZackAllen commented on xr_sample_project/Assets/SampleViewer/Samples/VRSample/Scripts/WeatherSystem.cs
> +    [SerializeField] Renderer cloudRenderer;
Make everything `private` that should be. Codemaid will do this.

2024-08-01 16:41 UTC, ZackAllen commented on xr_sample_project/Assets/SampleViewer/Samples/VRSample/Scripts/ActivateGrabRay.cs
> +// Copyright 2022 Esri.
These should all be 2024.

2024-08-07 16:50 UTC, mmgaw113 requested changes
Right off the bat, the sample wasn't working because there were no inputs for desktop XR. I had to add quest touch controllers to get it to work. I'm sure you have it working on your machine, so we need to make sure that the changes to that file get pushed.
<img width="803" alt="image" src="https://github.com/user-attachments/assets/6d713435-1f22-4e2d-80eb-6235ca04163d">

Second: Turning is not work at all. I'm not sure what binding it is supposed to go to, but I couldn't get it to work. There were some input action errors in the console
<img width="296" alt="image" src="https://github.com/user-attachments/assets/e4a90c3c-db08-4af1-985b-7ca69513391c">
<img width="298" alt="image" src="https://github.com/user-attachments/assets/9ac22ae3-2cf5-4b9d-9075-daf5047f890f">
<img width="314" alt="image" src="https://github.com/user-attachments/assets/be47b56a-b520-4b99-98d0-7ffa46e5d937">

Third: The right controller also wasn't working with the UI. I could only interact with the UI using the Left controller. Not a big deal, but we should be able to use both.

Forth: The Snow spawned too close to the ground. It was much further below me and just looked a bit weird.

Overall nice work. Fix these things and I'll retest for you. Let me know when it is ready.

2024-08-08 17:50 UTC, JayPShrestha commented
> Right off the bat, the sample wasn't working because there were no inputs for desktop XR. I had to add quest touch controllers to get it to work. I'm sure you have it working on your machine, so we need to make sure that the changes to that file get pushed. <img alt="image" width="803" src="https://private-user-images.githubusercontent.com/89485705/355906147-6d713435-1f22-4e2d-80eb-6235ca04163d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMzQ5NDUsIm5iZiI6MTcyMzEzNDY0NSwicGF0aCI6Ii84OTQ4NTcwNS8zNTU5MDYxNDctNmQ3MTM0MzUtMWYyMi00ZTJkLTgwZWItNjIzNWNhMDQxNjNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDE2MzA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxMGY3YjZkNWJmYjNjNTA5NTZlMzQ1OGM3MWI4OGRlZTM0MzNiMDg3ZWMwNzgxZDdlM2JlZjUwMGZjZmZlNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CNxpt7zxdFKmWiehtBRsdnJa7KFxwq1TuQqWKs75nU8">

This should be resolved with the latest commit

> 
> Second: Turning is not work at all. I'm not sure what binding it is supposed to go to, but I couldn't get it to work. There were some input action errors in the console <img alt="image" width="296" src="https://private-user-images.githubusercontent.com/89485705/355907078-e4a90c3c-db08-4af1-985b-7ca69513391c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMzQ5NDUsIm5iZiI6MTcyMzEzNDY0NSwicGF0aCI6Ii84OTQ4NTcwNS8zNTU5MDcwNzgtZTRhOTBjM2MtZGIwOC00YWYxLTk4NWItN2NhNjk1MTMzOTFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDE2MzA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwZGMyYjU4MGY3NmIwZjU5Njg4ZGMyZDY1YTM1NzBhNjJlMzdlOGY5ZDIzY2U5NmU4YzlmYTg3ZWQ0ZGU3NTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OJuIJBbP_E_uSa58w75gV2K1FCpn3KN-z2PU-mrBbz8"> <img alt="image" width="298" src="https://private-user-images.githubusercontent.com/89485705/355907195-9ac22ae3-2cf5-4b9d-9075-daf5047f890f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMzQ5NDUsIm5iZiI6MTcyMzEzNDY0NSwicGF0aCI6Ii84OTQ4NTcwNS8zNTU5MDcxOTUtOWFjMjJhZTMtMmNmNS00YjlkLTkwNzUtZGFmNTA0N2Y4OTBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDE2MzA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3MDQ5NzJiZDAzYjU2MjM0ZTJkYzcwMmQ0MTQ4ZGE2ODczMjA4YjFhNGE5MTIzMjE2NGJmYTYzNjIxYTUxY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lH3H2UzrZ1_yEzCDrGd-r4rVvsMmWW75mwjgxBElDT4"> <img alt="image" width="314" src="https://private-user-images.githubusercontent.com/89485705/355907342-be47b56a-b520-4b99-98d0-7ffa46e5d937.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMzQ5NDUsIm5iZiI6MTcyMzEzNDY0NSwicGF0aCI6Ii84OTQ4NTcwNS8zNTU5MDczNDItYmU0N2I1NmEtYjUyMC00Yjk5LTk4ZDAtN2ZmYTQ2ZTVkOTM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDE2MzA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhZTNkYWFhYTEwYTcwYWVkM2NjMzEwOTc2ZTg5MzQxOTc4YzE5MjUxNWVkMjUwOTZhYjg1ZmM2N2VjNTA1ZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bSTk5sEDmiWL60MuhwBSYqX0Pena7noJMwfLkk5-e3Q">
> 
> Third: The right controller also wasn't working with the UI. I could only interact with the UI using the Left controller. Not a big deal, but we should be able to use both.

This has been resolved with the latest commit

> 
> Forth: The Snow spawned too close to the ground. It was much further below me and just looked a bit weird.

This has been resolved with the latest commit


> 
> Overall nice work. Fix these things and I'll retest for you. Let me know when it is ready.


Everything should be fixed now, let me know if there's any problems

2024-08-08 19:24 UTC, ZackAllen commented on xr_sample_project/Assets/SampleViewer/Resources/SampleGraphicSettings/LightingManager.cs
> +           // Material skyMat = Resources.Load("Skybox/SkyboxLiteWarm", typeof(Material)) as Material;
Remove this, don't leave commented code.

2024-08-08 19:59 UTC, ZackAllen approved these changes

2024-08-15 21:04 UTC, mmgaw113 approved these changes
Functionality wise, everything looks good. Thanks for fixing those issues. I do have some nit picks in terms of weather and lighting but I don't think it is worth messing with because of URP limitations. It looks good as is and realistically I don't think the things I would list would be achievable given how URP works compared to HDRP. Might be worth discussing having a dedicated HDRP vr sample in the future 👀

2024-08-15 22:35 UTC, JayPShrestha commented
> Functionality wise, everything looks good. Thanks for fixing those issues. I do have some nit picks in terms of weather and lighting but I don't think it is worth messing with because of URP limitations. It looks good as is and realistically I don't think the things I would list would be achievable given how URP works compared to HDRP. Might be worth discussing having a dedicated HDRP vr sample in the future 👀

Funny you brought this up, I've spoken to I believe Zack and Jade about the idea of using HDRP because of the built-in cloud/sky/sun mechanics so that was something I had in mind, but yeah we'll see maybe that'll be a thing in a year, but okay I'll merge this in now!

2024-08-15 22:35 UTC, merged