Routing readme updates
Esri/arcgis-maps-sdk-unity-samples pull request #44
Opened 2022-09-07 15:39 UTC by tTakeda09

**Sample**

**Summary**

This PR is to improve the Readme

**Tests**

**ArcGIS Maps SDK Version**

2022-09-07 16:13 UTC, avr757 requested changes

2022-09-07 16:13 UTC, avr757 commented on samples_project/Assets/SampleViewer/Samples/Routing/readme.md
> +3. While holding shift, left click on the map twice. (This sample is only setup to work with mouse and keyboard.)
```suggestion
3. While holding shift, left click on the map twice. (This sample is only set up to work with mouse and keyboard.)
```

2022-09-07 21:43 UTC, Jade-JadeH approved these changes

2022-09-15 10:31 UTC, tTakeda09 commented on samples_project/Assets/SampleViewer/Samples/Routing/readme.md
> +3. While holding shift, left click on the map twice. (This sample is only set up to work with mouse and keyboard.)
```suggestion
1. Open the **Routing** level.
2. Click on the **RouteManager** game object under **ArcGISMap** in the **Hierarchy** window.
3. Set your API key in the **Inspector** window.
4. While holding shift, left click on the map twice. (This sample is only set up to work with mouse and keyboard.)
```

2022-09-15 10:32 UTC, tTakeda09 commented on samples_project/Assets/SampleViewer/Samples/Routing/readme.md
> +3. While holding shift, left click on the map twice. (This sample is only set up to work with mouse and keyboard.)
@Jade-JadeH @avr757 I'm not thinking of changing the sample level name but the sample name on doc.
So I think it's better to include the name of the sample level. What do you think?

2022-09-15 17:38 UTC, avr757 approved these changes

2022-10-03 22:57 UTC, Jade-JadeH approved these changes
looks good to me.

2022-10-05 10:28 UTC, tTakeda09 commented on samples_project/Assets/SampleViewer/Samples/Routing/readme.md
> +4. Use Unity's [Line Renderer component](https://docs.unity3d.com/Manual/class-LineRenderer.html) to draw the route.
```suggestion
1. The `HTTPClient` is used to query the [routing service's REST API](https://developers.arcgis.com/rest/network/api-reference/overview-of-network-analysis-services.htm). 
2. The sample makes a [direct request](https://developers.arcgis.com/rest/network/api-reference/route-synchronous-service.htm) to obtain the routing result.
3. The [Raycast](https://docs.unity3d.com/ScriptReference/Physics.Raycast.html) is used to determine the elevation at each breadcrumb's position to account for elevation. (Mesh colliders need to be enabled in the **ArcGIS Map** component to use the Raycast.)
4. Unity's [Line Renderer component](https://docs.unity3d.com/Manual/class-LineRenderer.html) are used to visualize the route segments between pairs of breadcrumbs.
```

2022-10-10 10:29 UTC, merged