Update readme.md
Esri/arcgis-maps-sdk-unity-samples pull request #47
Opened 2022-09-30 22:00 UTC by mmgaw113

**Sample**

Updates for the Readme File in the VR Sample

**Summary**

Changed which hands control what in the how to use, added a section addressing URP and HDRP and how HDRP will not work with Oculus Headsets, added controls for moving up and down in the world. 

**Tests**

N/A

**ArcGIS Maps SDK Version**

N/A

2022-09-30 22:10 UTC, Jade-JadeH commented on samples_project/Assets/SampleViewer/Samples/VRSample/readme.md
> +In order to use this sample, connect your headset to your computer and ensure it is detected properly. Upon loading the sample, place the headset on your head. It should automatically use the headset
just thought that users may not need to connect the headset if they deploy the app.

2022-09-30 22:10 UTC, Jade-JadeH commented on samples_project/Assets/SampleViewer/Samples/VRSample/readme.md
> +In order to use this sample, connect your headset to your computer and ensure it is detected properly. Upon loading the sample, place the headset on your head. It should automatically use the headset
```suggestion
1. Place the headset on your head. The sample should automatically use the headset to control the camera's position and rotation in the world. 
2. To move, use the joystick on the left controller, pushing the joystick will move you in that direction. The joystick on the right controller can be used to 'snap turn' 45 degrees, making it so you can turn around quickly. Additionally, pushing the right joystick up or down will allow the player to fly up or down in the world. 
```

2022-10-03 23:01 UTC, Jade-JadeH commented
after you make changes, please press request rereview to notify reviewers @mmgaw113

2022-10-03 23:01 UTC, Jade-JadeH approved these changes

2022-10-04 16:38 UTC, tTakeda09 requested changes
Please align the page section title and order with others. You can check the measure one.

2022-10-12 16:23 UTC, mrnelson6 commented
@tTakeda09 wanted you to update the title

2022-11-21 19:02 UTC, tTakeda09 commented on samples_project/Assets/SampleViewer/Samples/VRSample/readme.md
> +8. Press play and enjoy exploring.
This step looks more like How to use the sample and not How the sample is created to show the capability... If so, delete this line.

2022-11-23 16:44 UTC, mmgaw113 commented on samples_project/Assets/SampleViewer/Samples/VRSample/readme.md
> +# Simulate Virtual Reality
What about 'Simulate ArcGISMaps In Virtual Reality'?

2022-11-23 17:02 UTC, tTakeda09 commented on samples_project/Assets/SampleViewer/Samples/VRSample/readme.md
> +# Simulate Virtual Reality
I like it. If other Normandy like it too I think we can use that one because we don't have any other API doing this.

2022-11-23 18:07 UTC, tTakeda09 commented on samples_project/Assets/SampleViewer/Samples/VRSample/readme.md
> +## Provided Prefabs
I had a quick chat with Andy and we think it's better to move this information under How it works. It doesn't need to have a specific heading title. So remove the title `## Provided Prefabs` and put the text starting from `This sample provides...` under How it works before the step starts.

2022-11-23 18:11 UTC, tTakeda09 commented on samples_project/Assets/SampleViewer/Samples/VRSample/readme.md
> +This sample provides 3 prefabs for users to add to any scene making setup easy! The first prefab is the XR Origin prefab. This prefab holds all the components for tracking the VR headset and controll
```suggestion
This sample provides three Prefabs for users to add to any scene making setup easy! The first Prefab is the **XR Origin** Prefab. This Prefab holds all the components for tracking the VR headset and controllers, as well as the camera that renders components in the scene. The second Prefab is the **XR Interaction Manager**. This Prefab receives the input from the headset and controllers and allows the user to move their hands using the controllers as well as to control the rotation by moving their head with the headset on. Without this Prefab in the scene, the sample **will not work**. The last Prefab is the **Locomotion System** Prefab. This Prefab controls the movement in the sample, such as walking and flying around. 
```

2022-11-23 18:12 UTC, tTakeda09 commented on samples_project/Assets/SampleViewer/Samples/VRSample/readme.md
> +This sample provides 3 prefabs for users to add to any scene making setup easy! The first prefab is the XR Origin prefab. This prefab holds all the components for tracking the VR headset and controll
Another option is

```suggestion
This sample provides three Prefabs for users to add to any scene making setup easy! 
- XR Origin: This Prefab holds all the components for tracking the VR headset and controllers, as well as the camera that renders components in the scene. 
- XR Interaction Manager: This Prefab receives the input from the headset and controllers and allows the user to move their hands using the controllers as well as to control the rotation by moving their head with the headset on. Without this Prefab in the scene, the sample **will not work**. 
- Locomotion System: This Prefab controls the movement in the sample, such as walking and flying around. 
```

2022-11-23 18:13 UTC, tTakeda09 commented on samples_project/Assets/SampleViewer/Samples/VRSample/readme.md
> +6. Expand the **XR Origin** game object fully and select the Main Camera Game Object.
```suggestion
6. Expand the **XR Origin** game object fully and select the Main Camera game object.
```

2022-11-23 18:15 UTC, tTakeda09 commented on samples_project/Assets/SampleViewer/Samples/VRSample/readme.md
> +In order for the sample to run on Meta Headsets the device, must be placed in **Developer Mode**. Please refer to this [document](https://developer.Meta.com/documentation/native/android/mobile-device
```suggestion
In order for the sample to run on Meta Headsets, the device must be placed in **Developer Mode**. Please refer to this [document](https://developer.Meta.com/documentation/native/android/mobile-device-setup/) for how to perform such an action. This must be done for running the sample in the Unity Engine, making a build to run on Windows, or making a build directly to the headset (Meta Quest, Meta Quest 2, and Meta Quest Pro)
```

2022-11-23 18:17 UTC, tTakeda09 commented on samples_project/Assets/SampleViewer/Samples/VRSample/readme.md
> +This sample provides 3 prefabs for users to add to any scene making setup easy! The first prefab is the XR Origin prefab. This prefab holds all the components for tracking the VR headset and controll
Unity is formatting the word prefab like `Prefab` so we should follow.

2022-11-23 18:17 UTC, tTakeda09 commented on samples_project/Assets/SampleViewer/Samples/VRSample/readme.md
> +# Simulate ArcGISMaps In Virtual Reality
```suggestion
# Simulate ArcGISMaps in Virtual Reality
```

2022-11-28 17:28 UTC, merged